
const READY_STATE = "READY"
const CASH_COLLECTED_STATE = "CASH_COLLECTED"
const DISPENSE_ITEM_STATE = "DISPENSE_ITEM"
const DISPENSE_CHANGE_STATE = "DISPENSE_CHANGE"
const CANCEL_STATE = "CANCEL"

module.exports = {
    READY_STATE,
    CASH_COLLECTED_STATE,
    DISPENSE_ITEM_STATE,
    DISPENSE_CHANGE_STATE,
    CANCEL_STATE
}